
DROP TABLE klient CASCADE;
DROP TABLE znizka CASCADE;
DROP TABLE seans CASCADE;
DROP TABLE rezerwacja CASCADE;
DROP TABLE tworcy CASCADE;
DROP TABLE film CASCADE;
DROP TABLE sala CASCADE;
DROP TABLE miejsce CASCADE;
DROP TABLE bilet CASCADE;

CREATE TABLE znizka( 
	id_znizki INTEGER NOT NULL PRIMARY KEY,
	nazwa_znizki TEXT NOT NULL
);

CREATE TABLE klient( 
	id_klienta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
	imie VARCHAR(50) NOT NULL,
	nazwisko VARCHAR(50) NOT NULL,
	email VARCHAR(50) UNIQUE,
	nr_telefonu VARCHAR(50) NOT NULL,
	id_znizki INTEGER DEFAULT NULL REFERENCES znizka(id_znizki) ON UPDATE CASCADE ON DELETE RESTRICT
	);

CREATE TABLE film( 
	id_filmu INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	tytul TEXT NOT NULL, 
	gatunek TEXT,
	rok_premiery SMALLINT,
	czas_trwania INTEGER
	);

CREATE TABLE sala( 
	id_sali INTEGER NOT NULL PRIMARY KEY,
	liczba_miejsc INTEGER NOT NULL, 
	wolne_miejsca INTEGER
);

CREATE TABLE seans( 
	id_seansu INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_sali INTEGER NOT NULL REFERENCES sala(id_sali) ON UPDATE CASCADE ON DELETE RESTRICT, 
	id_filmu INTEGER NOT NULL REFERENCES film(id_filmu) ON UPDATE CASCADE ON DELETE CASCADE,
	data_seansu DATE NOT NULL,
	czas_rozpoczecia TIME NOT NULL,
	czas_zakonczenia TIME NOT NULL CHECK (czas_zakonczenia>czas_rozpoczecia),
	jezyk TEXT
);

CREATE TABLE rezerwacja( 
	id_rezerwacji INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_klienta INTEGER NOT NULL REFERENCES klient(id_klienta) ON UPDATE CASCADE ON DELETE RESTRICT, 
	id_seansu INTEGER NOT NULL REFERENCES seans(id_seansu) ON UPDATE CASCADE ON DELETE RESTRICT,
	status TEXT DEFAULT 'zarezerwowano'
);


CREATE TABLE tworcy(
    id_tworcy INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_filmu INTEGER NOT NULL REFERENCES film(id_filmu) ON UPDATE CASCADE ON DELETE RESTRICT,
	rezyser TEXT NOT NULL,
	scenariusz TEXT NOT NULL,
	obsada TEXT
);


CREATE TABLE miejsce(
	id_miejsca INTEGER NOT NULL PRIMARY KEY, 
	id_sali INTEGER NOT NULL REFERENCES sala(id_sali) ON UPDATE CASCADE ON DELETE RESTRICT,
	rzad INTEGER NOT NULL
);

CREATE TABLE bilet( 
	id_biletu INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_miejsca INTEGER NOT NULL REFERENCES miejsce(id_miejsca) ON UPDATE CASCADE ON DELETE RESTRICT, 
	id_rezerwacji INTEGER NOT NULL REFERENCES rezerwacja(id_rezerwacji) ON UPDATE CASCADE ON DELETE RESTRICT,
	id_znizki INTEGER DEFAULT NULL REFERENCES znizka(id_znizki) ON UPDATE CASCADE ON DELETE RESTRICT
);

INSERT INTO sala VALUES (1,200, 200);
INSERT INTO sala VALUES (2,150, 150);
INSERT INTO sala VALUES (3,100, 100);
INSERT INTO sala VALUES (4,70, 70);

INSERT INTO miejsce VALUES (1,1,1);
INSERT INTO miejsce VALUES (2,1,1);
INSERT INTO miejsce VALUES (3,1,1);
INSERT INTO miejsce VALUES (4,1,1);
INSERT INTO miejsce VALUES (5,1,1);
INSERT INTO miejsce VALUES (6,1,1);
INSERT INTO miejsce VALUES (7,1,1);
INSERT INTO miejsce VALUES (8,1,1);

INSERT INTO bilet(id_miejsca, id_rezerwacji) VALUES (5, 1);

INSERT INTO klient(imie, nazwisko, email, nr_telefonu) VALUES ('Jan', 'Kowalski', 'j.kowalsky@gmail.com', '892017233');
INSERT INTO klient(imie, nazwisko, email, nr_telefonu) VALUES ('Anna', 'Kowalska', 'anna.maria@wp.pl', '555321184');
INSERT INTO klien(imie, nazwisko, email, nr_telefonu)t VALUES ('Marek', 'Wiosło', 'wioslomarek@wp.pl', '737829102');
INSERT INTO klient(imie, nazwisko, email, nr_telefonu) VALUES ('Karolina', 'Wiatr', 'karowiatr@wp.pl', '772440000');
INSERT INTO klient(imie, nazwisko, email, nr_telefonu) VALUES ('Maria', 'Ruszkiewicz', 'maryrusz@gmail.com', '637829039');
INSERT INTO klient(imie, nazwisko, email, nr_telefonu) VALUES ('Ewelina', 'Miód', 'ewelina.miod@gmail.com', '666281920');
INSERT INTO klient(imie, nazwisko, email, nr_telefonu) VALUES ('Kacper', 'Kotlarek', 'kkotlsrek@wp.pl', '938444930');
INSERT INTO klient(imie, nazwisko, email, nr_telefonu) VALUES ('Sławomir', 'Nowak', 'slawek.nowak@gmail.com', '392003233');

INSERT INTO znizka VALUES(1, 'uczen');
INSERT INTO znizka VALUES(2, 'senior');
INSERT INTO znizka VALUES(3, 'rodzina');

INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Dom Gucci', 'dramat', 2021, 135);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Krime Story. Love Story.', 'komedia', 2022, 177);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Krzyk', 'horror', 2022, 120);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Batman', 'akcja', 2022, 176);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Zaułek Koszmarów', 'thriller', 2022, 150);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Wyjdź za Mnie', 'romantyczny', 2022, 112);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Wiki i Jej Sekret', 'familijny', 2022, 87);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Smierc na Nilu', 'kryminal', 2022, 127);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Benny & Joon', 'familijny', 2014, 99);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Beowulf', 'akcja', 1991, 133);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Best in Show', 'dramat', 2019, 184);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Best Laid Plans', 'dramat', 2004, 111);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('UHF', 'dramat', 1990, 137);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Ultimate Gift, The', 'dramat', 2005, 121);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Ultraviolet', 'horror', 1999, 180);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Unaccompanied Minors', 'kryminal', 2008, 168);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Unbreakable', 'komedia', 1999, 168);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Uncle Buck', 'familijny', 2006, 133);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Under Siege', 'akcja', 2018, 92);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Under the Tuscan Sun', 'familijny', 1993, 132);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Undercover Brother', 'romantyczny', 1990, 182);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Underdog', 'dramat', 2016, 184);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Best Little Whorehouse in Texas, The', 'familijny', 2022, 120);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Best Years of Our Lives, The', 'akcja', 1995, 121);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Better Off Dead', 'kryminal', 2003, 173);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Better Than Chocolate', 'familijny', 1997, 179);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Better Tomorrow, A', 'kryminal', 2009, 165);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Beverly Hills Chihuahua', 'horror', 2008, 112);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('TMNT', 'komedia', 1993, 142);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('To Catch a Thief', 'romantyczny', 2012, 133);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('To Have and Have Not', 'dramat', 2015, 121);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('To Kill a Mockingbird', 'familijny', 2018, 147);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('To Live and Die in L.A.', 'horror', 1994, 173);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Tolable David', 'romantyczny', 2020, 134);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Tom and Jerry: The Movie', 'romantyczny', 1993, 186);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Tom and Jerry: Willy Wonka and the Chocolate Factory', 'kryminal', 2012, 118);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Tomb Raider', 'hisotryczny', 2020, 105);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Tombstone', 'komedia', 2018, 152);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Tomcats', 'dramat', 1997, 108);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Tommy Boy', 'hisotryczny', 2011, 129);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Tomorrow Never Dies', 'horror', 2007, 160);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Tootsie', 'familijny', 2018, 125);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Top Cat: The Movie', 'romantyczny', 2016, 126);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Top Gun', 'komedia', 1992, 138);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Top Secret', 'kryminal', 2019, 123);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Beverly Hills Cop II', 'kryminal', 2019, 131);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Beverly Hills Cop III', 'hisotryczny', 2001, 187);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('V for Vendetta', 'dramat', 1994, 113);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Vacancy', 'kryminal', 2017, 169);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Valkyrie', 'akcja', 1991, 149);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Valley Girl', 'komedia', 1994, 185);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Vampire Bat', 'horror', 2010, 162);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Vampire in Brooklyn', 'hisotryczny', 1994, 140);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Vampires Suck', 'hisotryczny', 2016, 140);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Van Helsing', 'hisotryczny', 2004, 153);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Van Wilder', 'kryminal', 2005, 155);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Vanilla Sky', 'akcja', 1996, 117);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Bad Boys II', 'hisotryczny', 2000, 98);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Bad Day at Black Rock', 'dramat', 2020, 137);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Bad Santa', 'akcja', 1992, 129);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Bad Taste', 'komedia', 1994, 172);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Badlands', 'akcja', 2008, 132);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Balto', 'komedia', 1991, 148);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Bambi', 'akcja', 1999, 102);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Bambi II', 'akcja', 2014, 125);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Bananas', 'akcja', 2019, 158);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Barbarella', 'horror', 2011, 130);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Barbecue Brawl', 'dramat', 2005, 118);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Barcelona', 'komedia', 2009, 137);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Barneys Great Adventure', 'kryminal', 1991, 158);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Barry Lyndon', 'hisotryczny', 2018, 115);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Barton Fink', 'kryminal', 2011, 132);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('BASEketball', 'dramat', 2017, 136);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Cannibal! The Musical', 'romantyczny', 1998, 173);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Carbon Copy', 'horror', 1992, 190);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Carpool', 'komedia', 1995, 110);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Carry On Series, The', 'romantyczny', 1991, 168);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Catch That Kid', 'horror', 2007, 122);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Cats', 'kryminal', 2015, 174);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Catfight', 'dramat', 1999, 156);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Chutiya Mat Bana', 'kryminal', 1996, 133);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('The Castle of Cagliostro', 'dramat', 2013, 178);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Cats Meow', 'kryminal', 2018, 99);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Center Stage', 'hisotryczny', 2005, 168);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Chairman of the Board', 'romantyczny', 2018, 138);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Chances Are', 'familijny', 2015, 179);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Chandni Bar', 'hisotryczny', 1996, 150);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Changeling, The', 'akcja', 1997, 90);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Charly', 'familijny', 2015, 108);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Chaos', 'dramat', 2020, 132);
INSERT INTO film(tytul, gatunek, rok_premiery, czas_trwania) VALUES('Cheats', 'horror', 2006, 185);


INSERT INTO tworcy VALUES(1, 1, 'Ridley Scott', 'Roberto Bentivegna', 'Lady Gaga, Adam Driver, Jared Leto, Jeremy Irons, Al Pacino, Salma Hayek' );
INSERT INTO tworcy VALUES(2, 2, 'Michał Węgrzyn', 'Michał Węgrzyn, Kali', '
Wiktoria Gąsiewska, Cezary Łukaszewicz, Michał Koterski, Agnieszka Więdłocha, Małgorzata Kożuchowska, Piotr Witkowski, Gabriela Muskała, Jan Frycz, Cezary Żak, Vienio');
INSERT INTO tworcy VALUES(3, 3, 'Matt Bettinelli-Olpin, Tyler Gillett', 'James Vanderbilt, Guy Busick');
INSERT INTO tworcy VALUES(4, 4, 'Matt Reeves', 'Matt Reeves; Peter Craig', '	Robert Pattinson, Zoë Kravitz, Paul Dano, Jeffrey Wright, John Turturro, Peter Sarsgaard, Andy Serkis, Colin Farrell');
INSERT INTO tworcy VALUES(5, 5, 'Guillermo del Toro', 'Kim Morgan, Guillermo del Toro', 'Bradley Cooper, Cate Blanchett, Rooney Mara, Willem Dafoe, Ron Perlman');
INSERT INTO tworcy VALUES(6, 6, 'Kat Coiro', 'John Rogers, Tami Sagher, Harper Dill','Jennifer Lopez, Owen Wilson, Utkarsh Ambudkar, Jimmy Fallon, Maluma');
INSERT INTO tworcy VALUES(7, 7, 'Denis Imbert','Denis Imbert, Mathieu Oullion, Rémi Sappe', 'Shanna Keil, Vincent Elbaz, Tchéky Karyo');
INSERT INTO tworcy VALUES(8, 8, 'Kenneth Branagh','Michael Green', 'Kenneth Branagh, Gal Gadot, Armie Hammer, Emma Mackey, Russell Brand
');
INSERT INTO tworcy VALUES(9, 9, 'James Clavell', 'Rene Balcer');
INSERT INTO tworcy VALUES(10, 10, 'Laurie Anderson', 'Alexander Baron');
INSERT INTO tworcy VALUES(11, 11, 'Robert De Niro', 'Ingmar Bergman');
INSERT INTO tworcy VALUES(12, 12, 'John A. Davis', 'Luc Besson');
INSERT INTO tworcy VALUES(13, 13, 'Larry David', 'Joy Isi Bewaji');
INSERT INTO tworcy VALUES(14, 14, 'Dave Halls', 'Brad Bird');
INSERT INTO tworcy VALUES(15, 15, 'Van Darkholme', 'James Bridie');
INSERT INTO tworcy VALUES(16, 16, 'Joe Dante', 'Shane Black');
INSERT INTO tworcy VALUES(17, 17, 'Billy Crystal', 'Olly Blackburn');
INSERT INTO tworcy VALUES(18, 18, 'Michael Crichton', 'Frits Bolkestein');
INSERT INTO tworcy VALUES(19, 19, 'Woody Allen', 'Uwe Boll');
INSERT INTO tworcy VALUES(20, 20, 'Tim Allen', 'Robert Bolt');
INSERT INTO tworcy VALUES(21, 21, 'Sherman Alexie', 'Edward Bond');
INSERT INTO tworcy VALUES(22, 22, 'Alan Alda', 'Bong Joon-ho');
INSERT INTO tworcy VALUES(23, 23, 'Asa Akira', 'Jorge Luis Borges');
INSERT INTO tworcy VALUES(24, 24, 'Leonardo DiCaprio', 'Melvyn Bragg');
INSERT INTO tworcy VALUES(25, 25, 'Scott Derrickson', 'Bertolt Brecht');
INSERT INTO tworcy VALUES(26, 26, 'Johnny Depp', 'Fausto Brizzi');
INSERT INTO tworcy VALUES(27, 27, 'Cecil B. DeMille', 'Ricou Browning');
INSERT INTO tworcy VALUES(28, 28, 'Fred Dekker', 'Jackie Chan');
INSERT INTO tworcy VALUES(29, 29, 'Robert De Niro', 'Coen brothers');
INSERT INTO tworcy VALUES(30, 30, 'John A. Davis', 'Peter Corey');
INSERT INTO tworcy VALUES(31, 31, 'Larry David', 'A. J. Cronin');
INSERT INTO tworcy VALUES(32, 32, 'Dave Halls', 'Charles Dance');
INSERT INTO tworcy VALUES(33, 33, 'Van Darkholme', 'Russell T Davies');
INSERT INTO tworcy VALUES(34, 34, 'Joe Dante', 'Isla Dewar');
INSERT INTO tworcy VALUES(35, 35, 'Billy Crystal', 'Farrukh Dhondy');
INSERT INTO tworcy VALUES(36, 36, 'Michael Crichton', 'Cameron Duncan');
INSERT INTO tworcy VALUES(37, 37, 'Scott Crary', 'Marriott Edgar');
INSERT INTO tworcy VALUES(38, 38, 'Caroline Cousteau', 'Warren Ellis');
INSERT INTO tworcy VALUES(39, 39, 'Don Coscarelli', 'Laura Esquivel');
INSERT INTO tworcy VALUES(40, 40, 'Roger Corman', 'Julian Fellowes');
INSERT INTO tworcy VALUES(41, 41, 'Merian C. Cooper', 'George MacDonald Fraser');
INSERT INTO tworcy VALUES(42, 42, 'Tony Conrad', 'Gabriel Byrne');
INSERT INTO tworcy VALUES(43, 43, 'Gregory Colbert', 'Helen Garner');
INSERT INTO tworcy VALUES(44, 44, 'Rob Cohen', 'Ritwik Ghatak');
INSERT INTO tworcy VALUES(45, 45, 'Coen brothers', 'Giancarlo Giannini');
INSERT INTO tworcy VALUES(46, 46, 'George Clooney', 'Karen Gillan');
INSERT INTO tworcy VALUES(47, 47, 'James Clavell', 'Aki KaurismĂ¤ki');
INSERT INTO tworcy VALUES(48, 48, 'Daniel Chong', 'Naomi Kawase');
INSERT INTO tworcy VALUES(49, 49, 'Don Cheadle', 'Krzysztof KieĹ›lowski');
INSERT INTO tworcy VALUES(50, 50, 'Chris Carter)', 'Ephraim Kishon');
INSERT INTO tworcy VALUES(51, 51, 'John Carpenter', 'Arthur Koestler');
INSERT INTO tworcy VALUES(52, 52, 'Frank Capra', 'Tim Kring');
INSERT INTO tworcy VALUES(53, 53, 'Julia Cameron', 'Lisa Kudrow');
INSERT INTO tworcy VALUES(54, 54, 'David Byrne', 'Akira Kurosawa');
INSERT INTO tworcy VALUES(55, 55, 'Tim Burton', 'Alex Kurtzman');
INSERT INTO tworcy VALUES(56, 56, 'Ken Burns', 'Dany LaferriĂ¨re');
INSERT INTO tworcy VALUES(57, 57, 'Chris Buck', 'Noel Langley');
INSERT INTO tworcy VALUES(58, 58, 'Ricou Browning', 'Lee Chang-dong');
INSERT INTO tworcy VALUES(59, 59, 'Mel Brooks', 'Dennis Lehane');
INSERT INTO tworcy VALUES(60, 60, 'James L. Brooks', 'Elmore Leonard');
INSERT INTO tworcy VALUES(61, 61, 'Marlon Brando', 'Graham Linehan');
INSERT INTO tworcy VALUES(62, 62, 'Zach Braff', 'Christopher Logue');
INSERT INTO tworcy VALUES(63, 63, 'Don Bluth', 'Lou Ye');
INSERT INTO tworcy VALUES(64, 64, 'Jeff Bleckner', 'Dolph Lundgren');
INSERT INTO tworcy VALUES(65, 65, 'William Peter Blatty', 'Bernard MacLaverty');
INSERT INTO tworcy VALUES(66, 66, 'Michael Ian Black', 'William H. Macy');
INSERT INTO tworcy VALUES(67, 67, 'Brad Bird', 'Naguib Mahfouz');
INSERT INTO tworcy VALUES(68, 68, 'Anna Biller', 'Marcello Marchesi');
INSERT INTO tworcy VALUES(69, 69, 'Maggie Betts', 'Wataru Mimura');
INSERT INTO tworcy VALUES(70, 70, 'Amber Benson', 'Hayao Miyazaki');
INSERT INTO tworcy VALUES(71, 71, 'Robert Benchley', 'Moon So-ri');
INSERT INTO tworcy VALUES(72, 72, 'Lake Bell', 'Alberto Moravia');
INSERT INTO tworcy VALUES(73, 73, 'L. Frank Baum', 'Miho Mosulishvili');
INSERT INTO tworcy VALUES(74, 74, 'Saul Bass', 'Charles Mudede');
INSERT INTO tworcy VALUES(75, 75, 'Jules Bass', 'Usama Mukwaya');
INSERT INTO tworcy VALUES(76, 76, 'Toni Basil', 'Aiysha Saagar');
INSERT INTO tworcy VALUES(77, 77, 'Drew Barrymore', 'Amy Sherman-Palladino');
INSERT INTO tworcy VALUES(78, 78, 'Steve Bannon', 'Sia (musician)');
INSERT INTO tworcy VALUES(79, 79, 'Robert Banks', 'Michael Marshall Smith');
INSERT INTO tworcy VALUES(80, 80, 'Artur Balder', 'Stephen Sommers');
INSERT INTO tworcy VALUES(81, 81, 'Ralph Bakshi', 'J. Michael Straczynski');
INSERT INTO tworcy VALUES(82, 82, 'Bruce Baillie', 'Osamu Tezuka');
INSERT INTO tworcy VALUES(83, 83, 'Paul Auster', 'Guillermo del Toro');
INSERT INTO tworcy VALUES(84, 84, 'J. J. Abrams', 'Igor Vishnevetsky');
INSERT INTO tworcy VALUES(85, 85, 'Jack Arnold)', 'James Wan');
INSERT INTO tworcy VALUES(86, 86, 'Laurie Anderson', 'Irvine Welsh');
INSERT INTO tworcy VALUES(87, 87, 'Woody Allen', 'Lina WertmĂĽller');
INSERT INTO tworcy VALUES(88, 88, 'Tim Allen', 'Jack Whitehall');
INSERT INTO tworcy VALUES(89, 89, 'Sherman Alexie', 'Geert Wilders');
INSERT INTO tworcy VALUES(90, 90, 'Alan Alda', 'Wong Kar-wai');
INSERT INTO tworcy VALUES(91, 91, 'Asa Akira', 'Balaraba Ramat Yakubu');




